@echo off
echo Starting development server...
start "Dev Server" cmd /k "set DATABASE_URL=file:./dev.db&& npm run dev"

echo Waiting for server to start...
echo Waiting for server to start (8s)...
timeout /t 8 /nobreak >nul

echo Running UI tests...
echo Running UI tests in headed mode (PLAYWRIGHT_HEADLESS=0)...
set PLAYWRIGHT_HEADLESS=0
node tests/ui.test.js

echo.
echo Tests completed. Press any key to exit...
pause >nul
